# Default values for Projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
revisionHistoryCount: 5

image:
  repository: lightregistry.azurecr.io/camel-quarkus-gradle-ci_prd:latest
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

environment: "Homolog"

public_hostname: enviroment.domain.com

public_endpoint: "/"

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true

resources:
  limits:
    cpu: "1"
  requests:
    cpu: 150m

nodeSelector: {}

tolerations: []

affinity: {}

openshift:
  enabled: true

volumes:
  name: secretpocplaybook
  secret:
    secretName: secretpocplaybook
    defaultMode: 420

volumeMounts:
  name: secretpocplaybook
  mountPath: /tmp/certificate

envFrom:
  configMapRef:
    name: poc-playbooks-cfg-map
  secretRef:
    name: poc-playbooks-keys

secret:
  metadata:
    name: secretpocplaybook

