{{- if not .Values.openshift.enabled -}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "camel-quarkus-gradle.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "camel-quarkus-gradle.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.public_hostname }}
    secretName: {{ .Values.public_hostname }}.tls
  rules:
    - host: {{ .Values.public_hostname }}
      http:
        paths:
          - path: {{ .Values.public_endpoint }}($|/)(.*)
            backend:
              serviceName: camel-quarkus-gradle
              servicePort: {{ .Values.service.port }}
{{- end }}
{{- end }}