pool:
  vmImage: $(vmImageAZ)
  
stages:
- stage: TagAndPush
  displayName: Tag And Push
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
  jobs:
  - job: TagAndPush
    displayName: Tag And Push
    steps:
    - task: gitversion/setup@0
      displayName: Install GitTools
      inputs:
        versionSpec: '5.6.8'
    - task: gitversion/execute@0
      displayName: Use GitVersion  
    - script: |
        sudo az login -u '$(azLoginMacmiller)' -p '$(azSenhaMacmiller)' -t '$(tenantId)'
        sudo az acr login --name '$(containerRegistryAbreviado)'
        sudo docker pull '$(containerRegistry)/$(imageRepository)_hlg:latest'
        sudo docker tag '$(containerRegistry)/$(imageRepository)_hlg:latest' '$(containerRegistry)/$(imageRepository)_prd:$(tag1)'
        sudo docker tag '$(containerRegistry)/$(imageRepository)_hlg:latest' '$(containerRegistry)/$(imageRepository)_prd:latest'
      displayName: Tagging

    - task: Docker@2
      displayName: Push ACR
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)_prd'
        command: 'push'
        tags: '$(tag1)'

    - task: Docker@2
      displayName: Push ACR latest
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)_prd'
        command: 'push'
        tags: 'latest'

        