stages:
- stage: UnitTest
  displayName: Unit Test
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: SonarCloud
    displayName: SonarCloud
    pool:
      vmImage: '$(vmImageAZ)'
    steps:
    - checkout: poc-playbooks-fase3
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sc-sonarcloud'
        organization: 'arquiteturacorporativalight'
        scannerMode: 'Other'
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
  - job: UnitTest
    displayName: Unit Test
    dependsOn: SonarCloud
    pool:
      vmImage: '$(vmImageAZ)'
    steps:
    - checkout: poc-playbooks-fase3
    - task: gitversion/setup@0
      displayName: Install GitTools
      inputs:
        versionSpec: '5.6.8'
    - task: gitversion/execute@0
      displayName: Use GitVersion
    - task: Cache@2
      inputs:
        key: 'v1 | gradle | $(Agent.OS) | $(Build.Repository.LocalPath)/build.gradle'
        path: /home/vsts/.gradle/caches/
      displayName: Gradle Caching
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        options: --build-cache -PartifactId=$(projectId) -Pversion=$(GitVersion.MajorMinorPatch) 
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'test'
      displayName: Build Test
    - script: |
        ./gradlew --stop
      failOnStderr: true    
      displayName: Gradle Stop