stages:

- stage: UnitTest
  displayName: Unit Test
  jobs:
  - job: UnitTest
    displayName: Unit Test
    pool:
      vmImage: '$(vmImageAZ)'
    steps:
    - task: gitversion/setup@0
      displayName: Install GitTools
      inputs:
        versionSpec: '5.6.8'
    - task: gitversion/execute@0
      displayName: Use GitVersion
    - task: RestoreAndSaveCache@1
      inputs:
        keyfile: 'gradlew | $(Agent.OS)'
        targetfolder: '$(Pipeline.Workspace)/.gradle/caches/'
        vstsFeed: '$(ArtifactFeedGradleCache)'
        platformIndependent: true
    - script: |
        sudo sh ./gradlew --build-cache test -PartifactId=$(projectId) -Pversion=$(tag1)   
        sudo sh ./gradlew --stop    
      displayName: Build Test
      condition: ne(variables['CacheRestored'], 'true')

- stage: BuildandPublish
  displayName: Build and Publish
  dependsOn: UnitTest
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: BuildandPublish
    displayName: Build and Publish
    pool:
      vmImage: '$(vmImageAZ)'
    steps:
    - task: gitversion/setup@0
      displayName: Install GitTools
      inputs:
        versionSpec: '5.6.8'
    - task: gitversion/execute@0
      displayName: Use GitVersion
    - task: RestoreCache@1
        inputs:
          keyfile: 'gradlew | $(Agent.OS)'
          targetfolder: '$(Pipeline.Workspace)/.gradle/caches/'
          vstsFeed: '$(ArtifactFeedGradleCache)'
          platformIndependent: true
    - script: |
        sudo sh ./gradlew --build-cache build -x test -PartifactId=$(projectId) -Pversion=$(tag1) -Dquarkus.container-image.build=true -Dquarkus.container-image.group=$(containerRegistry) -Dquarkus.container-image.name=$(imageRepository)   
        sudo sh ./gradlew --stop    
      displayName: Build
      condition: ne(variables['CacheRestored'], 'true')
    - script: |
        sudo docker tag '$(containerRegistry)/$(imageRepository):$(tag1)' '$(containerRegistry)/$(imageRepository)_hlg:$(tag1)-$(tag2)'
        sudo docker tag '$(containerRegistry)/$(imageRepository):$(tag1)' '$(containerRegistry)/$(imageRepository)_hlg:latest'
      displayName: Tagging
    - task: Docker@2
      displayName: Push ACR
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)_hlg'
        command: 'push'
        tags: '$(tag1)-$(tag2)'
    - task: Docker@2
      displayName: Push ACR latest
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)_hlg'
        command: 'push'
        tags: 'latest'
        