stages:
- stage: TagAndPush
  displayName: Tag And Push
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
  jobs:
  - deployment: Approval
    displayName: Approval
    environment: poc-playbooks
  - job: TagAndPush
    dependsOn: Approval
    displayName: Tag And Push
    pool:
      vmImage: $(vmImageAZ)
    steps:
    - checkout: poc-playbooks
    - task: gitversion/setup@0
      displayName: Install GitTools
      inputs:
        versionSpec: '5.6.8'
    - task: gitversion/execute@0
      displayName: Use GitVersion  
    - script: |
        sudo az login -u '$(azLoginACR)' -p '$(azSenhaACR)' -t '$(tenantId)'
        sudo az acr login --name '$(containerRegistryName)'
        sudo docker pull '$(containerRegistryFullName)/$(imageRepository)_hlg:latest'
        sudo docker tag '$(containerRegistryFullName)/$(imageRepository)_hlg:latest' '$(containerRegistryFullName)/$(imageRepository)_prd:$(GitVersion.MajorMinorPatch)'
        sudo docker tag '$(containerRegistryFullName)/$(imageRepository)_hlg:latest' '$(containerRegistryFullName)/$(imageRepository)_prd:latest'
      failOnStderr: true
      displayName: Tagging

    - task: Docker@2
      displayName: Push ACR
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)_prd'
        command: 'push'
        tags: '$(GitVersion.MajorMinorPatch)'

    - task: Docker@2
      displayName: Push ACR latest
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)_prd'
        command: 'push'
        tags: 'latest'