stages:

- stage: UnitTest
  displayName: Unit Test
  jobs:
  - job: UnitTest
    displayName: Unit Test
    pool:
      vmImage: '$(vmImageAZ)'
    steps:
    - task: gitversion/setup@0
      displayName: Install GitTools
      inputs:
        versionSpec: '5.6.8'
    - task: gitversion/execute@0
      displayName: Use GitVersion
    - task: Cache@2
      displayName: Gradle Caches
      inputs:
        key: 'gradle | "$(Agent.OS)"'
        path: /home/vsts/.gradle/caches/
    - script: |
        ls -la /home/vsts/.gradle/caches/
        ls -la /home/vsts/.gradle/caches/build-cache-1    
      displayName: listando cache
    - script: |
        ./gradlew --build-cache test -PartifactId=$(projectId) -Pversion=$(GitVersion.MajorMinorPatch)  
        ./gradlew --stop    
      displayName: Build Test
    - script: |
        ls -la /home/vsts/.gradle/caches/
        ls -la /home/vsts/.gradle/caches/build-cache-1    
      displayName: listando cache