stages:
- stage: CheckOutHelmRepo
  displayName: Check Out Helm Repo
  dependsOn: UnitTest
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: helm
    displayName: helm
    pool:
      vmImage: '$(vmImageAZ)'
    steps:
    - checkout: devops-repo-yaml
    - script: dir $(Build.SourcesDirectory)
    - task: HelmInstaller@1
      displayName: Install Helm 3.5.4
      inputs:
        helmVersionToInstall: '3.5.4'
    - task: Bash@3
      displayName: Helm lint
      inputs:
        targetType: 'inline'
        script: |
          helm lint java/gradle/templates/$(projectId)/helm/chart
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: |
          java/gradle/templates/$(projectId)/helm/chart/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)/'
        OverWrite: true
      displayName: Copy Files
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/java/gradle/templates/$(projectId)/helm/chart'
        ArtifactName: 'helm'
        publishLocation: 'Container'
      displayName: Publish and Build Artifacts