stages:
- stage: Release
  displayName: Release
  #dependsOn: CheckOutHelmRepo
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: DeployHomolog
    displayName: Deploy Homolog
    environment: poc-playbooks
    pool:
      vmImage: '$(vmImageAZ)'
    steps:
    - task: oc-cmd@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'sc-sa-az-devops'
        cmd: oc project
      displayName: OpenShift Connect
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'specific'
        project: '$(projectId)'
        pipeline: '$(projectId)-hlg'
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        artifactName: 'helm'
        downloadPath: '$(Build.ArtifactStagingDirectory)'
      displayName: Download Build Artifacts
    - task: HelmDeploy@0
      inputs:
        connectionType: 'None'
        namespace: '$(projectId)-hlg'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: '$(Build.ArtifactStagingDirectory)/helm'
        releaseName: '$(projectId)-hlg'
        overrideValues: 'image.repository=lightregistry.azurecr.io/$(projectId)_hlg,image.tag=0.3.1-hlg'
        force: true
      displayName: Helm Deploy