stages:
- stage: Release
  displayName: Release
  #dependsOn: CheckOutHelmRepo
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: Release
    displayName: Release
    pool:
      vmImage: '$(vmImageAZ)'
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'specific'
        project: '$(projectId)'
        pipeline: '$(projectId)-hlg'
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        artifactName: 'helm'
        downloadPath: '$(Build.ArtifactStagingDirectory)/java/gradle/templates/$(projectId)/helm'
    - task: oc-cmd@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'sc-sa-az-devops'
        cmd: oc project
    - task: HelmInstaller@1
      displayName: Install Helm 3.5.4
      inputs:
        helmVersionToInstall: '3.5.4'
    - task: Bash@3
      displayName: Helm lint
      inputs:
        targetType: 'inline'
        script: |
          helm lint java/gradle/templates/$(projectId)/helm
        failOnStderr: true
    - script: |
        helm upgrade --namespace $(projectId)-hlg --install --set image.repository=lightregistry.azurecr.io/$(projectId)_hlg:latest --wait --timeout 600s --history-max 5 $(projectId)-hlg $(Build.ArtifactStagingDirectory)/java/gradle/templates/$(projectId)/helm