stages:
- stage: UnitTest
  displayName: Unit Test
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: UnitTest
    displayName: Unit Test
    pool:
      vmImage: '$(vmImageAZ)'
    steps:
    - checkout: poc-playbooks
    - task: gitversion/setup@0
      displayName: Install GitTools
      inputs:
        versionSpec: '5.6.8'
    - task: gitversion/execute@0
      displayName: Use GitVersion
    - bash: |
        echo "##vso[task.setvariable variable=HOME_DIRECTORY;]$HOME"
      displayName: Set Variable
    - task: Cache@2
      inputs:
        key: |
          gradle | "$(Agent.OS)"
        restoreKeys: |
          gradle | "$(Agent.OS)"
          gradle
        path: /home/vsts/.gradle/caches/
      displayName: Gradle Caching
    - script: |
        echo $(Agent.OS)
        ls -la /home/vsts/.gradle/caches/build-cache-1
      displayName: Listando arquivos de cache
    - script: |
        ./gradlew test --build-cache -PartifactId=$(projectId) -Pversion=$(GitVersion.MajorMinorPatch)  
        ./gradlew --stop
      failOnStderr: true    
      displayName: Build Test