stages:
- stage: UnitTest
  displayName: Unit Test
  jobs:
  - job: UnitTest
    displayName: Unit Test
    pool:
      vmImage: '$(vmImageAZ)'
    steps:
    - checkout: poc-playbooks
    - script: dir $(Build.SourcesDirectory)
    - task: gitversion/setup@0
      displayName: Install GitTools
      inputs:
        versionSpec: '5.6.8'
    - task: gitversion/execute@0
      displayName: Use GitVersion
    - bash: |
        echo "##vso[task.setvariable variable=HOME_DIRECTORY;]$HOME"
      displayName: Set Variable
    - task: Cache@2
      displayName: Gradle Caches
      inputs:
        key: 'gradle | "$(Agent.OS)"'
        path: $(GradleCache)
    - script: |
        ./gradlew --build-cache test -PartifactId=$(projectId) -Pversion=$(GitVersion.MajorMinorPatch)  
        ./gradlew --stop
      failOnStderr: true    
      displayName: Build Test